package l2s.gameserver.network.l2.s2c;

import l2s.gameserver.model.Player;
import l2s.gameserver.model.items.PcInventory;
import l2s.gameserver.utils.Location;

public class GMViewCharacterInfo extends L2GameServerPacket
{
	private Location _loc;
	private PcInventory _inv;
	private int obj_id;
	private int _race;
	private int _sex;
	private int class_id;
	private int pvp_flag;
	private int karma;
	private int level;
	private int mount_type;
	private int _str;
	private int _con;
	private int _dex;
	private int _int;
	private int _wit;
	private int _men;
	private int _sp;
	private int curHp;
	private int maxHp;
	private int curMp;
	private int maxMp;
	private int curCp;
	private int maxCp;
	private int curLoad;
	private int maxLoad;
	private int rec_left;
	private int rec_have;
	private int _patk;
	private int _patkspd;
	private int _pdef;
	private int evasion;
	private int accuracy;
	private int crit;
	private int _matk;
	private int _matkspd;
	private int _mdef;
	private int hair_style;
	private int hair_color;
	private int face;
	private int gm_commands;
	private int clan_id;
	private int clan_crest_id;
	private int ally_id;
	private int title_color;
	private int noble;
	private int hero;
	private int private_store;
	private int name_color;
	private int pk_kills;
	private int pvp_kills;
	private int _runSpd;
	private int _walkSpd;
	private int _swimSpd;
	private int DwarvenCraftLevel;
	private int running;
	private int pledge_class;
	private String _name;
	private String title;
	private long _exp;
	private float move_speed;
	private float attack_speed;
	private double col_radius;
	private double col_height;

	public GMViewCharacterInfo(final Player cha)
	{
		_inv = cha.getInventory();
		_loc = cha.getLoc();
		obj_id = cha.getObjectId();
		_name = cha.getName();
		_race = cha.getRace().ordinal();
		_sex = cha.getSex();
		class_id = cha.getClassId().getId();
		level = cha.getLevel();
		_exp = cha.getExp();
		_str = cha.getSTR();
		_dex = cha.getDEX();
		_con = cha.getCON();
		_int = cha.getINT();
		_wit = cha.getWIT();
		_men = cha.getMEN();
		curHp = (int) cha.getCurrentHp();
		maxHp = cha.getMaxHp();
		curMp = (int) cha.getCurrentMp();
		maxMp = cha.getMaxMp();
		_sp = cha.getSp();
		curLoad = cha.getCurrentLoad();
		maxLoad = cha.getMaxLoad();
		_patk = cha.getPAtk(null);
		_patkspd = cha.getPAtkSpd();
		_pdef = cha.getPDef(null);
		evasion = cha.getEvasionRate(null);
		accuracy = cha.getAccuracy();
		crit = cha.getCriticalHit(null, null);
		_matk = cha.getMAtk(null, null);
		_matkspd = cha.getMAtkSpd();
		_mdef = cha.getMDef(null, null);
		pvp_flag = cha.getPvpFlag();
		karma = cha.getKarma();
		move_speed = cha.getMovementSpeedMultiplier();
		_runSpd = (int) (cha.getRunSpeed() / move_speed);
		_walkSpd = (int) (cha.getWalkSpeed() / move_speed);
		_swimSpd = cha.getSwimSpeed();
		attack_speed = cha.getAttackSpeedMultiplier();
		mount_type = cha.getMountType();
		col_radius = cha.getCollisionRadius();
		col_height = cha.getCollisionHeight();
		hair_style = cha.getHairStyle();
		hair_color = cha.getHairColor();
		face = cha.getFace();
		gm_commands = cha.isGM() ? 1 : 0;
		title = cha.getTitle();
		clan_id = cha.getClanId();
		clan_crest_id = cha.getClanCrestId();
		ally_id = cha.getAllyId();
		private_store = cha.getPrivateStoreType();
		DwarvenCraftLevel = Math.max(cha.getSkillLevel(1320), 0);
		pk_kills = cha.getPkKills();
		pvp_kills = cha.getPvpKills();
		rec_left = cha.getRecomLeft();
		rec_have = cha.getRecomHave();
		curCp = (int) cha.getCurrentCp();
		maxCp = cha.getMaxCp();
		running = cha.isRunning() ? 1 : 0;
		pledge_class = cha.getPledgeClass();
		noble = cha.isNoble() ? 1 : 0;
		hero = cha.isHero() ? 1 : 0;
		name_color = cha.getNameColor();
		title_color = cha.getTitleColor();
	}

	@Override
	protected final void writeImpl()
	{
		writeC(143);
		writeD(_loc.getX());
		writeD(_loc.getY());
		writeD(_loc.getZ());
		writeD(_loc.h);
		writeD(obj_id);
		writeS((CharSequence) _name);
		writeD(_race);
		writeD(_sex);
		writeD(class_id);
		writeD(level);
		writeQ(_exp);
		writeD(_str);
		writeD(_dex);
		writeD(_con);
		writeD(_int);
		writeD(_wit);
		writeD(_men);
		writeD(maxHp);
		writeD(curHp);
		writeD(maxMp);
		writeD(curMp);
		writeD(_sp);
		writeD(curLoad);
		writeD(maxLoad);
		writeD(40);
		writeD(_inv.getPaperdollObjectId(16));
		writeD(_inv.getPaperdollObjectId(2));
		writeD(_inv.getPaperdollObjectId(1));
		writeD(_inv.getPaperdollObjectId(3));
		writeD(_inv.getPaperdollObjectId(5));
		writeD(_inv.getPaperdollObjectId(4));
		writeD(_inv.getPaperdollObjectId(6));
		writeD(_inv.getPaperdollObjectId(7));
		writeD(_inv.getPaperdollObjectId(8));
		writeD(_inv.getPaperdollObjectId(9));
		writeD(_inv.getPaperdollObjectId(10));
		writeD(_inv.getPaperdollObjectId(11));
		writeD(_inv.getPaperdollObjectId(12));
		writeD(_inv.getPaperdollObjectId(13));
		writeD(_inv.getPaperdollObjectId(7));
		writeD(_inv.getPaperdollObjectId(15));
		writeD(_inv.getPaperdollObjectId(16));
		writeD(_inv.getPaperdollItemId(16));
		writeD(_inv.getPaperdollItemId(2));
		writeD(_inv.getPaperdollItemId(1));
		writeD(_inv.getPaperdollItemId(3));
		writeD(_inv.getPaperdollItemId(5));
		writeD(_inv.getPaperdollItemId(4));
		writeD(_inv.getPaperdollItemId(6));
		writeD(_inv.getPaperdollItemId(7));
		writeD(_inv.getPaperdollItemId(8));
		writeD(_inv.getPaperdollItemId(9));
		writeD(_inv.getPaperdollItemId(10));
		writeD(_inv.getPaperdollItemId(11));
		writeD(_inv.getPaperdollItemId(12));
		writeD(_inv.getPaperdollItemId(13));
		writeD(_inv.getPaperdollItemId(7));
		writeD(_inv.getPaperdollItemId(15));
		writeD(_inv.getPaperdollItemId(16));
		for(int i = 0; i < 34; ++i)
			writeH(0);
		writeD(_patk);
		writeD(_patkspd);
		writeD(_pdef);
		writeD(evasion);
		writeD(accuracy);
		writeD(crit);
		writeD(_matk);
		writeD(_matkspd);
		writeD(_patkspd);
		writeD(_mdef);
		writeD(pvp_flag);
		writeD(karma);
		writeD(_runSpd);
		writeD(_walkSpd);
		writeD(_swimSpd);
		writeD(_swimSpd);
		writeD(_runSpd);
		writeD(_walkSpd);
		writeD(_runSpd);
		writeD(_walkSpd);
		writeF((double) move_speed);
		writeF((double) attack_speed);
		writeF(col_radius);
		writeF(col_height);
		writeD(hair_style);
		writeD(hair_color);
		writeD(face);
		writeD(gm_commands);
		writeS((CharSequence) title);
		writeD(clan_id);
		writeD(clan_crest_id);
		writeD(ally_id);
		writeC(mount_type);
		writeC(private_store);
		writeC(DwarvenCraftLevel);
		writeD(pk_kills);
		writeD(pvp_kills);
		writeH(rec_left);
		writeH(rec_have);
		writeD(class_id);
		writeD(0);
		writeD(maxCp);
		writeD(curCp);
		writeC(running);
		writeC(321);
		writeD(pledge_class);
		writeC(noble);
		writeC(hero);
		writeD(name_color);
		writeD(title_color);
	}
}
